global:
  checkNewVersion: true
  sendAnonymousUsage: false
# traefik.yml - UPDATED FOR TRAEFIK v3
api:
  dashboard: true
  insecure: true  # For testing only
  debug: true
log:
  level: DEBUG
entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"
# certificatesresolvers:
#   myresolver:
#     acme:
#       email: ea.cloudhost@gmail.com
#       storage: /var/traefic/certs/acme.json
#       httpChallenge:
#         entryPoint: web
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

experimental:
  plugins:
    traefik-coraza-waf:
      moduleName: "github.com/jcchavezs/coraza-http-wasm-traefik"
      version: "v0.3.0"